# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e530676e980e0ac60fe6a943793257c671a41059b9791d81ff3e500f813cb6c00e6f544a8e7720cafdadff3f62c496591a02e3076338e75ad9a187d996c176d9

test:
  secret_key_base: 877255351eca6cf767828e370731afaead05f011486581f887f2c94c9321bb6e9a47f604c3771eacd3a323303fafd532daeac8a4dfff1e6662763f77588ef90a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
